# Gruvbox Dark, medium contrast (bg0 = #282828, fg1 = #ebdbb2)
# Palette: https://github.com/morhetz/gruvbox

background              #282828
foreground              #ebdbb2
selection_background    #504945
selection_foreground    #ebdbb2

cursor                  #ebdbb2
cursor_text_color       #282828

url_color               #83a598

# Borders
active_border_color     #8ec07c
inactive_border_color   #504945
bell_border_color       #fe8019

# Tabs
active_tab_background    #8ec07c
active_tab_foreground    #282828
inactive_tab_background  #3c3836
inactive_tab_foreground  #a89984

# Marks
mark1_foreground #282828
mark1_background #8ec07c
mark2_foreground #282828
mark2_background #fabd2f
mark3_foreground #282828
mark3_background #d3869b

# black
color0 #282828
color8 #928374

# red
color1 #cc241d
color9 #fb4934

# green
color2 #98971a
color10 #b8bb26

# yellow
color3 #d79921
color11 #fabd2f

# blue
color4 #458588
color12 #83a598

# magenta
color5 #b16286
color13 #d3869b

# cyan
color6 #689d6a
color14 #8ec07c

# white
color7 #a89984
color15 #ebdbb2
