general {
    lock_cmd = pgrep hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
}

listener {
    timeout = 30
    on-timeout = pidof hyprlock && hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

listener {
    timeout = 15000
    on-timeout = /run/current-system/sw/bin/brightnessctl -s set 10
    on-resume = /run/current-system/sw/bin/brightnessctl -r
}

listener {
    timeout = 60000
    on-timeout = /run/current-system/sw/bin/brightnessctl -sd dell::kbd_backlight set 0
    on-resume = /run/current-system/sw/bin/brightnessctl -rd rgb:kbd_backlight
}

listener {
    timeout = 90000
    on-timeout = loginctl lock-session
}

listener {
    timeout = 93000
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

listener {
    timeout = 180000
    on-timeout = systemctl suspend
}
