
# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = false

[character]
success_symbol = '[➜](bold green) '
error_symbol = '[✗](bold red) '
vimcmd_symbol = '[V](bold green) '

[directory]
truncation_length = 8
truncation_symbol = '…/'
format = '[$read_only]($read_only_style) [$path]($style) '
read_only = '[]'

[package]
disabled = true

[status]
style = 'bg:blue'
symbol = ' '
success_symbol = ' '
not_found_symbol = ' '
format = '[$symbol$signal_name$maybe_int]($style) '
map_symbol = true
disabled = true

[memory_usage]
disabled = true
threshold = -1
symbol = ' '
style = 'bold dimmed green'

[sudo]
style = 'bold green'
symbol = ' '
disabled = false

[username]
style_user = 'white bold'
style_root = 'black bold'
format = '[$user]($style) '
disabled = true
show_always = true
